### ISSUE TITLE
ReflectionException: Class "Webkul\Attribute\Http\Requests\AttributeForm" does not exist in Krayin CRM v2.0.1 REST API

### ISSUE THREAD

**Issue by fitulka** [krayin/rest-api#8]
Description:

After installing the latest commit 121c25b of the rest-api package on Krayin CRM v2.0.1, I encountered the following error when trying to create a new contact using the API:

**Request:**
curl -X 'POST' \
  'https://crm.example.com/api/v1/contacts/persons' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer 1|HznFUL2xut1UpxjGcQM8cDW3NjJiRgfjRDUYrvJYe48fb0a2' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRF-TOKEN: ' \
  -d '{
  "name": "Role",
  "emails": [
    {
      "value": "jhon.doe@mail.com",
      "label": "work"
    }
  ],
  "contact_numbers": [
    {
      "value": "09315981404",
      "label": "work"
    }
  ],
  "organization_id": 1,
  "entity_type": "persons"
}'

**Response:**
{
  "message": "Class \"Webkul\\Attribute\\Http\\Requests\\AttributeForm\" does not exist",
  "exception": "ReflectionException",
  "file": "/var/www/htdocs/example.com/crm/vendor/laravel/framework/src/Illuminate/Routing/ResolvesRouteDependencies.php",
  "line": 81,
  "trace": [...]
}

**Steps to Reproduce:**

1. Install the latest commit 121c25b from the rest-api repository.
2. Attempt to create a new contact via the API using the /api/v1/contacts/persons endpoint.
3. The error occurs with a ReflectionException stating that the AttributeForm class does not exist.

**Expected Behavior:** The API should correctly handle the request and create a new contact.

**Environment:**

Krayin CRM v2.0.1
REST API Package Commit 121c25b
PHP 8.2.x

**Additional Context:** It seems that the Webkul\\Attribute\\Http\\Requests\\AttributeForm class might be missing or not properly registered within the application.

**Comment by suraj-webkul** [comment]
This issue has been fixed in [this pr](https://github.com/krayin/rest-api/pull/9).
